name: 'My first container action'
description: 'For A cloud guru'
author: 'Semab Tariq'
inputs:
  myInput:
    description: 'Hi There!'
    required: true
    default: 'Awesome Guru'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
